name: Deploy Front App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build -- --configuration production

      - name: List dist output
        run: ls -R dist

      ## =====================================
      ## 1️⃣ BACKUP DEL ÚLTIMO DEPLOY
      ## =====================================
      - name: Backup old front
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo "Backup del front anterior..."
            if [ -d "/var/www/mesero-front" ]; then
              sudo rm -rf /var/www/mesero-front-backup
              sudo mkdir -p /var/www/mesero-front-backup
              sudo cp -r /var/www/mesero-front/* /var/www/mesero-front-backup/ || true
              echo "Backup creado en /var/www/mesero-front-backup"
            else
              echo "No existe /var/www/mesero-front (primer deploy?)"
            fi

      ## =====================================
      ## 2️⃣ LIMPIAR CARPETA DEL FRONT
      ## =====================================
      - name: Clean target folder
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo "Limpiando carpeta del front..."
            sudo rm -rf /var/www/mesero-front/*
            echo "Carpeta limpia."

      ## =====================================
      ## 3️⃣ SUBIR LA NUEVA BUILD
      ## =====================================
      - name: Copy files to server via SSH
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          # mandamos la carpeta browser completa
          source: "dist/metor-angular/browser"
          target: "/var/www/mesero-front"
          overwrite: true
          strip_components: 3
